// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: bft.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber    int64                  `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	NodeID        string                 `protobuf:"bytes,4,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Result        int64                  `protobuf:"varint,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_bft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionResponse) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *TransactionResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionResponse) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TransactionResponse) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *TransactionResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type SignedTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *TransactionResponse   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTransactionResponse) Reset() {
	*x = SignedTransactionResponse{}
	mi := &file_bft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransactionResponse) ProtoMessage() {}

func (x *SignedTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignedTransactionResponse) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{1}
}

func (x *SignedTransactionResponse) GetMessage() *TransactionResponse {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedTransactionResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_bft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TransactionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type SignedTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *TransactionRequest    `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTransactionRequest) Reset() {
	*x = SignedTransactionRequest{}
	mi := &file_bft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransactionRequest) ProtoMessage() {}

func (x *SignedTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignedTransactionRequest) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{3}
}

func (x *SignedTransactionRequest) GetRequest() *TransactionRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *SignedTransactionRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_bft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{4}
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PrePrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber    int64                  `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePrepareMessage) Reset() {
	*x = PrePrepareMessage{}
	mi := &file_bft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePrepareMessage) ProtoMessage() {}

func (x *PrePrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePrepareMessage.ProtoReflect.Descriptor instead.
func (*PrePrepareMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{5}
}

func (x *PrePrepareMessage) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrePrepareMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *PrePrepareMessage) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type SignedPrePrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *PrePrepareMessage     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Request       *TransactionRequest    `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPrePrepareMessage) Reset() {
	*x = SignedPrePrepareMessage{}
	mi := &file_bft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPrePrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPrePrepareMessage) ProtoMessage() {}

func (x *SignedPrePrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPrePrepareMessage.ProtoReflect.Descriptor instead.
func (*SignedPrePrepareMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{6}
}

func (x *SignedPrePrepareMessage) GetMessage() *PrePrepareMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedPrePrepareMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedPrePrepareMessage) GetRequest() *TransactionRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type PrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber    int64                  `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	NodeID        string                 `protobuf:"bytes,4,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	mi := &file_bft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessage.ProtoReflect.Descriptor instead.
func (*PrepareMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{7}
}

func (x *PrepareMessage) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrepareMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *PrepareMessage) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PrepareMessage) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type SignedPrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *PrepareMessage        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPrepareMessage) Reset() {
	*x = SignedPrepareMessage{}
	mi := &file_bft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPrepareMessage) ProtoMessage() {}

func (x *SignedPrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPrepareMessage.ProtoReflect.Descriptor instead.
func (*SignedPrepareMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{8}
}

func (x *SignedPrepareMessage) GetMessage() *PrepareMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedPrepareMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CollectedSignedPrepareMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ViewNumber    int64                   `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	SequenceNum   int64                   `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Digest        []byte                  `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Messages      []*SignedPrepareMessage `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectedSignedPrepareMessage) Reset() {
	*x = CollectedSignedPrepareMessage{}
	mi := &file_bft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectedSignedPrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectedSignedPrepareMessage) ProtoMessage() {}

func (x *CollectedSignedPrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectedSignedPrepareMessage.ProtoReflect.Descriptor instead.
func (*CollectedSignedPrepareMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{9}
}

func (x *CollectedSignedPrepareMessage) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *CollectedSignedPrepareMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *CollectedSignedPrepareMessage) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CollectedSignedPrepareMessage) GetMessages() []*SignedPrepareMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type CommitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber    int64                  `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	NodeID        string                 `protobuf:"bytes,4,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMessage) Reset() {
	*x = CommitMessage{}
	mi := &file_bft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessage) ProtoMessage() {}

func (x *CommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessage.ProtoReflect.Descriptor instead.
func (*CommitMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{10}
}

func (x *CommitMessage) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *CommitMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *CommitMessage) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CommitMessage) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type SignedCommitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *CommitMessage         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedCommitMessage) Reset() {
	*x = SignedCommitMessage{}
	mi := &file_bft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedCommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedCommitMessage) ProtoMessage() {}

func (x *SignedCommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedCommitMessage.ProtoReflect.Descriptor instead.
func (*SignedCommitMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{11}
}

func (x *SignedCommitMessage) GetMessage() *CommitMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedCommitMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CollectedSignedCommitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber    int64                  `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Messages      []*SignedCommitMessage `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectedSignedCommitMessage) Reset() {
	*x = CollectedSignedCommitMessage{}
	mi := &file_bft_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectedSignedCommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectedSignedCommitMessage) ProtoMessage() {}

func (x *CollectedSignedCommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectedSignedCommitMessage.ProtoReflect.Descriptor instead.
func (*CollectedSignedCommitMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{12}
}

func (x *CollectedSignedCommitMessage) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *CollectedSignedCommitMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *CollectedSignedCommitMessage) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CollectedSignedCommitMessage) GetMessages() []*SignedCommitMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// TODO: SignedPrePrepareMessage contains the original request also...not ideal
type PrepareProof struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	SignedPrePrepareMessage *SignedPrePrepareMessage `protobuf:"bytes,1,opt,name=signedPrePrepareMessage,proto3" json:"signedPrePrepareMessage,omitempty"`
	SignedPrepareMessages   []*SignedPrepareMessage  `protobuf:"bytes,2,rep,name=signedPrepareMessages,proto3" json:"signedPrepareMessages,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PrepareProof) Reset() {
	*x = PrepareProof{}
	mi := &file_bft_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareProof) ProtoMessage() {}

func (x *PrepareProof) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareProof.ProtoReflect.Descriptor instead.
func (*PrepareProof) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{13}
}

func (x *PrepareProof) GetSignedPrePrepareMessage() *SignedPrePrepareMessage {
	if x != nil {
		return x.SignedPrePrepareMessage
	}
	return nil
}

func (x *PrepareProof) GetSignedPrepareMessages() []*SignedPrepareMessage {
	if x != nil {
		return x.SignedPrepareMessages
	}
	return nil
}

type ViewChangeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber    int64                  `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	PreparedSet   []*PrepareProof        `protobuf:"bytes,3,rep,name=preparedSet,proto3" json:"preparedSet,omitempty"`
	NodeID        string                 `protobuf:"bytes,4,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewChangeMessage) Reset() {
	*x = ViewChangeMessage{}
	mi := &file_bft_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewChangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewChangeMessage) ProtoMessage() {}

func (x *ViewChangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewChangeMessage.ProtoReflect.Descriptor instead.
func (*ViewChangeMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{14}
}

func (x *ViewChangeMessage) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *ViewChangeMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *ViewChangeMessage) GetPreparedSet() []*PrepareProof {
	if x != nil {
		return x.PreparedSet
	}
	return nil
}

func (x *ViewChangeMessage) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type SignedViewChangeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ViewChangeMessage     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedViewChangeMessage) Reset() {
	*x = SignedViewChangeMessage{}
	mi := &file_bft_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedViewChangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedViewChangeMessage) ProtoMessage() {}

func (x *SignedViewChangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedViewChangeMessage.ProtoReflect.Descriptor instead.
func (*SignedViewChangeMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{15}
}

func (x *SignedViewChangeMessage) GetMessage() *ViewChangeMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedViewChangeMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type NewViewMessage struct {
	state                    protoimpl.MessageState     `protogen:"open.v1"`
	ViewNumber               int64                      `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	SignedViewChangeMessages []*SignedViewChangeMessage `protobuf:"bytes,2,rep,name=signedViewChangeMessages,proto3" json:"signedViewChangeMessages,omitempty"`
	SignedPrePrepareMessages []*SignedPrePrepareMessage `protobuf:"bytes,3,rep,name=signedPrePrepareMessages,proto3" json:"signedPrePrepareMessages,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *NewViewMessage) Reset() {
	*x = NewViewMessage{}
	mi := &file_bft_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewMessage) ProtoMessage() {}

func (x *NewViewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewMessage.ProtoReflect.Descriptor instead.
func (*NewViewMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{16}
}

func (x *NewViewMessage) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *NewViewMessage) GetSignedViewChangeMessages() []*SignedViewChangeMessage {
	if x != nil {
		return x.SignedViewChangeMessages
	}
	return nil
}

func (x *NewViewMessage) GetSignedPrePrepareMessages() []*SignedPrePrepareMessage {
	if x != nil {
		return x.SignedPrePrepareMessages
	}
	return nil
}

type SignedNewViewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *NewViewMessage        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedNewViewMessage) Reset() {
	*x = SignedNewViewMessage{}
	mi := &file_bft_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedNewViewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedNewViewMessage) ProtoMessage() {}

func (x *SignedNewViewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedNewViewMessage.ProtoReflect.Descriptor instead.
func (*SignedNewViewMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{17}
}

func (x *SignedNewViewMessage) GetMessage() *NewViewMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedNewViewMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_bft_proto protoreflect.FileDescriptor

const file_bft_proto_rawDesc = "" +
	"\n" +
	"\tbft.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\"\x9b\x01\n" +
	"\x13TransactionResponse\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x16\n" +
	"\x06nodeID\x18\x04 \x01(\tR\x06nodeID\x12\x16\n" +
	"\x06result\x18\x05 \x01(\x03R\x06result\"l\n" +
	"\x19SignedTransactionResponse\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x17.pb.TransactionResponseR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"}\n" +
	"\x12TransactionRequest\x121\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0f.pb.TransactionR\vtransaction\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\"j\n" +
	"\x18SignedTransactionRequest\x120\n" +
	"\arequest\x18\x01 \x01(\v2\x16.pb.TransactionRequestR\arequest\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"m\n" +
	"\vTransaction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"m\n" +
	"\x11PrePrepareMessage\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\"\x9a\x01\n" +
	"\x17SignedPrePrepareMessage\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.pb.PrePrepareMessageR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x120\n" +
	"\arequest\x18\x03 \x01(\v2\x16.pb.TransactionRequestR\arequest\"\x82\x01\n" +
	"\x0ePrepareMessage\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x16\n" +
	"\x06nodeID\x18\x04 \x01(\tR\x06nodeID\"b\n" +
	"\x14SignedPrepareMessage\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.pb.PrepareMessageR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xaf\x01\n" +
	"\x1dCollectedSignedPrepareMessage\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x124\n" +
	"\bmessages\x18\x04 \x03(\v2\x18.pb.SignedPrepareMessageR\bmessages\"\x81\x01\n" +
	"\rCommitMessage\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x16\n" +
	"\x06nodeID\x18\x04 \x01(\tR\x06nodeID\"`\n" +
	"\x13SignedCommitMessage\x12+\n" +
	"\amessage\x18\x01 \x01(\v2\x11.pb.CommitMessageR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xad\x01\n" +
	"\x1cCollectedSignedCommitMessage\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x123\n" +
	"\bmessages\x18\x04 \x03(\v2\x17.pb.SignedCommitMessageR\bmessages\"\xb5\x01\n" +
	"\fPrepareProof\x12U\n" +
	"\x17signedPrePrepareMessage\x18\x01 \x01(\v2\x1b.pb.SignedPrePrepareMessageR\x17signedPrePrepareMessage\x12N\n" +
	"\x15signedPrepareMessages\x18\x02 \x03(\v2\x18.pb.SignedPrepareMessageR\x15signedPrepareMessages\"\xa1\x01\n" +
	"\x11ViewChangeMessage\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x122\n" +
	"\vpreparedSet\x18\x03 \x03(\v2\x10.pb.PrepareProofR\vpreparedSet\x12\x16\n" +
	"\x06nodeID\x18\x04 \x01(\tR\x06nodeID\"h\n" +
	"\x17SignedViewChangeMessage\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.pb.ViewChangeMessageR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xe2\x01\n" +
	"\x0eNewViewMessage\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12W\n" +
	"\x18signedViewChangeMessages\x18\x02 \x03(\v2\x1b.pb.SignedViewChangeMessageR\x18signedViewChangeMessages\x12W\n" +
	"\x18signedPrePrepareMessages\x18\x03 \x03(\v2\x1b.pb.SignedPrePrepareMessageR\x18signedPrePrepareMessages\"b\n" +
	"\x14SignedNewViewMessage\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.pb.NewViewMessageR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature2\xf9\x03\n" +
	"\x0eLinearPBFTNode\x12G\n" +
	"\x0fTransferRequest\x12\x1c.pb.SignedTransactionRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x0fReadOnlyRequest\x12\x1c.pb.SignedTransactionRequest\x1a\x1d.pb.SignedTransactionResponse\x12C\n" +
	"\n" +
	"PrePrepare\x12\x1b.pb.SignedPrePrepareMessage\x1a\x18.pb.SignedPrepareMessage\x12E\n" +
	"\aPrepare\x12!.pb.CollectedSignedPrepareMessage\x1a\x17.pb.SignedCommitMessage\x12B\n" +
	"\x06Commit\x12 .pb.CollectedSignedCommitMessage\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\n" +
	"ViewChange\x12\x1b.pb.SignedViewChangeMessage\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\aNewView\x12\x18.pb.SignedNewViewMessage\x1a\x16.google.protobuf.Empty2\\\n" +
	"\x13LinearPBFTClientApp\x12E\n" +
	"\fReceiveReply\x12\x1d.pb.SignedTransactionResponse\x1a\x16.google.protobuf.EmptyB%Z#github.com/mavleo96/bft-mavleo96/pbb\x06proto3"

var (
	file_bft_proto_rawDescOnce sync.Once
	file_bft_proto_rawDescData []byte
)

func file_bft_proto_rawDescGZIP() []byte {
	file_bft_proto_rawDescOnce.Do(func() {
		file_bft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bft_proto_rawDesc), len(file_bft_proto_rawDesc)))
	})
	return file_bft_proto_rawDescData
}

var file_bft_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_bft_proto_goTypes = []any{
	(*TransactionResponse)(nil),           // 0: pb.TransactionResponse
	(*SignedTransactionResponse)(nil),     // 1: pb.SignedTransactionResponse
	(*TransactionRequest)(nil),            // 2: pb.TransactionRequest
	(*SignedTransactionRequest)(nil),      // 3: pb.SignedTransactionRequest
	(*Transaction)(nil),                   // 4: pb.Transaction
	(*PrePrepareMessage)(nil),             // 5: pb.PrePrepareMessage
	(*SignedPrePrepareMessage)(nil),       // 6: pb.SignedPrePrepareMessage
	(*PrepareMessage)(nil),                // 7: pb.PrepareMessage
	(*SignedPrepareMessage)(nil),          // 8: pb.SignedPrepareMessage
	(*CollectedSignedPrepareMessage)(nil), // 9: pb.CollectedSignedPrepareMessage
	(*CommitMessage)(nil),                 // 10: pb.CommitMessage
	(*SignedCommitMessage)(nil),           // 11: pb.SignedCommitMessage
	(*CollectedSignedCommitMessage)(nil),  // 12: pb.CollectedSignedCommitMessage
	(*PrepareProof)(nil),                  // 13: pb.PrepareProof
	(*ViewChangeMessage)(nil),             // 14: pb.ViewChangeMessage
	(*SignedViewChangeMessage)(nil),       // 15: pb.SignedViewChangeMessage
	(*NewViewMessage)(nil),                // 16: pb.NewViewMessage
	(*SignedNewViewMessage)(nil),          // 17: pb.SignedNewViewMessage
	(*emptypb.Empty)(nil),                 // 18: google.protobuf.Empty
}
var file_bft_proto_depIdxs = []int32{
	0,  // 0: pb.SignedTransactionResponse.message:type_name -> pb.TransactionResponse
	4,  // 1: pb.TransactionRequest.transaction:type_name -> pb.Transaction
	2,  // 2: pb.SignedTransactionRequest.request:type_name -> pb.TransactionRequest
	5,  // 3: pb.SignedPrePrepareMessage.message:type_name -> pb.PrePrepareMessage
	2,  // 4: pb.SignedPrePrepareMessage.request:type_name -> pb.TransactionRequest
	7,  // 5: pb.SignedPrepareMessage.message:type_name -> pb.PrepareMessage
	8,  // 6: pb.CollectedSignedPrepareMessage.messages:type_name -> pb.SignedPrepareMessage
	10, // 7: pb.SignedCommitMessage.message:type_name -> pb.CommitMessage
	11, // 8: pb.CollectedSignedCommitMessage.messages:type_name -> pb.SignedCommitMessage
	6,  // 9: pb.PrepareProof.signedPrePrepareMessage:type_name -> pb.SignedPrePrepareMessage
	8,  // 10: pb.PrepareProof.signedPrepareMessages:type_name -> pb.SignedPrepareMessage
	13, // 11: pb.ViewChangeMessage.preparedSet:type_name -> pb.PrepareProof
	14, // 12: pb.SignedViewChangeMessage.message:type_name -> pb.ViewChangeMessage
	15, // 13: pb.NewViewMessage.signedViewChangeMessages:type_name -> pb.SignedViewChangeMessage
	6,  // 14: pb.NewViewMessage.signedPrePrepareMessages:type_name -> pb.SignedPrePrepareMessage
	16, // 15: pb.SignedNewViewMessage.message:type_name -> pb.NewViewMessage
	3,  // 16: pb.LinearPBFTNode.TransferRequest:input_type -> pb.SignedTransactionRequest
	3,  // 17: pb.LinearPBFTNode.ReadOnlyRequest:input_type -> pb.SignedTransactionRequest
	6,  // 18: pb.LinearPBFTNode.PrePrepare:input_type -> pb.SignedPrePrepareMessage
	9,  // 19: pb.LinearPBFTNode.Prepare:input_type -> pb.CollectedSignedPrepareMessage
	12, // 20: pb.LinearPBFTNode.Commit:input_type -> pb.CollectedSignedCommitMessage
	15, // 21: pb.LinearPBFTNode.ViewChange:input_type -> pb.SignedViewChangeMessage
	17, // 22: pb.LinearPBFTNode.NewView:input_type -> pb.SignedNewViewMessage
	1,  // 23: pb.LinearPBFTClientApp.ReceiveReply:input_type -> pb.SignedTransactionResponse
	18, // 24: pb.LinearPBFTNode.TransferRequest:output_type -> google.protobuf.Empty
	1,  // 25: pb.LinearPBFTNode.ReadOnlyRequest:output_type -> pb.SignedTransactionResponse
	8,  // 26: pb.LinearPBFTNode.PrePrepare:output_type -> pb.SignedPrepareMessage
	11, // 27: pb.LinearPBFTNode.Prepare:output_type -> pb.SignedCommitMessage
	18, // 28: pb.LinearPBFTNode.Commit:output_type -> google.protobuf.Empty
	18, // 29: pb.LinearPBFTNode.ViewChange:output_type -> google.protobuf.Empty
	18, // 30: pb.LinearPBFTNode.NewView:output_type -> google.protobuf.Empty
	18, // 31: pb.LinearPBFTClientApp.ReceiveReply:output_type -> google.protobuf.Empty
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_bft_proto_init() }
func file_bft_proto_init() {
	if File_bft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bft_proto_rawDesc), len(file_bft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_bft_proto_goTypes,
		DependencyIndexes: file_bft_proto_depIdxs,
		MessageInfos:      file_bft_proto_msgTypes,
	}.Build()
	File_bft_proto = out.File
	file_bft_proto_goTypes = nil
	file_bft_proto_depIdxs = nil
}
