// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: bft.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestSet       int64                  `protobuf:"varint,1,opt,name=testSet,proto3" json:"testSet,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_bft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetTestSet() int64 {
	if x != nil {
		return x.TestSet
	}
	return 0
}

func (x *StatusRequest) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitBalance   int64                  `protobuf:"varint,1,opt,name=initBalance,proto3" json:"initBalance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_bft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{1}
}

func (x *ResetRequest) GetInitBalance() int64 {
	if x != nil {
		return x.InitBalance
	}
	return 0
}

type TransactionResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber int64                  `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	Timestamp  int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sender     string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	NodeID     string                 `protobuf:"bytes,4,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Result     int64                  `protobuf:"varint,5,opt,name=result,proto3" json:"result,omitempty"`
	// For compatibality with ycsb benchmarking
	ResultData    map[string][]byte `protobuf:"bytes,6,rep,name=resultData,proto3" json:"resultData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Field-value map for read operations
	ScanResults   []*ScanResult     `protobuf:"bytes,7,rep,name=scanResults,proto3" json:"scanResults,omitempty"`                                                                         // Multiple results for scan operations
	Error         string            `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`                                                                                     // Error message if operation failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_bft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionResponse) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *TransactionResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionResponse) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TransactionResponse) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *TransactionResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TransactionResponse) GetResultData() map[string][]byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *TransactionResponse) GetScanResults() []*ScanResult {
	if x != nil {
		return x.ScanResults
	}
	return nil
}

func (x *TransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ScanResult represents a single scan result
type ScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string][]byte      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResult) Reset() {
	*x = ScanResult{}
	mi := &file_bft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResult) ProtoMessage() {}

func (x *ScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResult.ProtoReflect.Descriptor instead.
func (*ScanResult) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{3}
}

func (x *ScanResult) GetFields() map[string][]byte {
	if x != nil {
		return x.Fields
	}
	return nil
}

type SignedTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *TransactionResponse   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTransactionResponse) Reset() {
	*x = SignedTransactionResponse{}
	mi := &file_bft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransactionResponse) ProtoMessage() {}

func (x *SignedTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignedTransactionResponse) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{4}
}

func (x *SignedTransactionResponse) GetMessage() *TransactionResponse {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedTransactionResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_bft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TransactionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type SignedTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *TransactionRequest    `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTransactionRequest) Reset() {
	*x = SignedTransactionRequest{}
	mi := &file_bft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransactionRequest) ProtoMessage() {}

func (x *SignedTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignedTransactionRequest) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{6}
}

func (x *SignedTransactionRequest) GetRequest() *TransactionRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *SignedTransactionRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Transaction struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Sender   string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver string                 `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount   int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// For compatibality with ycsb benchmarking
	Table         string            `protobuf:"bytes,5,opt,name=table,proto3" json:"table,omitempty"`
	Key           string            `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Values        map[string][]byte `protobuf:"bytes,7,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fields        []string          `protobuf:"bytes,8,rep,name=fields,proto3" json:"fields,omitempty"`
	StartKey      string            `protobuf:"bytes,9,opt,name=startKey,proto3" json:"startKey,omitempty"`
	ScanCount     int64             `protobuf:"varint,10,opt,name=scanCount,proto3" json:"scanCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_bft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{7}
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *Transaction) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Transaction) GetValues() map[string][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Transaction) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Transaction) GetStartKey() string {
	if x != nil {
		return x.StartKey
	}
	return ""
}

func (x *Transaction) GetScanCount() int64 {
	if x != nil {
		return x.ScanCount
	}
	return 0
}

type PrePrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber    int64                  `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePrepareMessage) Reset() {
	*x = PrePrepareMessage{}
	mi := &file_bft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePrepareMessage) ProtoMessage() {}

func (x *PrePrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePrepareMessage.ProtoReflect.Descriptor instead.
func (*PrePrepareMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{8}
}

func (x *PrePrepareMessage) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrePrepareMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *PrePrepareMessage) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type SignedPrePrepareMessage struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Message       *PrePrepareMessage        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                    `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Request       *SignedTransactionRequest `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPrePrepareMessage) Reset() {
	*x = SignedPrePrepareMessage{}
	mi := &file_bft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPrePrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPrePrepareMessage) ProtoMessage() {}

func (x *SignedPrePrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPrePrepareMessage.ProtoReflect.Descriptor instead.
func (*SignedPrePrepareMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{9}
}

func (x *SignedPrePrepareMessage) GetMessage() *PrePrepareMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedPrePrepareMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedPrePrepareMessage) GetRequest() *SignedTransactionRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type PrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber    int64                  `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	NodeID        string                 `protobuf:"bytes,4,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	mi := &file_bft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessage.ProtoReflect.Descriptor instead.
func (*PrepareMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{10}
}

func (x *PrepareMessage) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrepareMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *PrepareMessage) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PrepareMessage) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type SignedPrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *PrepareMessage        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Signature2    []byte                 `protobuf:"bytes,3,opt,name=signature2,proto3" json:"signature2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPrepareMessage) Reset() {
	*x = SignedPrepareMessage{}
	mi := &file_bft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPrepareMessage) ProtoMessage() {}

func (x *SignedPrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPrepareMessage.ProtoReflect.Descriptor instead.
func (*SignedPrepareMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{11}
}

func (x *SignedPrepareMessage) GetMessage() *PrepareMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedPrepareMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedPrepareMessage) GetSignature2() []byte {
	if x != nil {
		return x.Signature2
	}
	return nil
}

type CommitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber    int64                  `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	NodeID        string                 `protobuf:"bytes,4,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMessage) Reset() {
	*x = CommitMessage{}
	mi := &file_bft_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessage) ProtoMessage() {}

func (x *CommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessage.ProtoReflect.Descriptor instead.
func (*CommitMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{12}
}

func (x *CommitMessage) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *CommitMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *CommitMessage) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CommitMessage) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type SignedCommitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *CommitMessage         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedCommitMessage) Reset() {
	*x = SignedCommitMessage{}
	mi := &file_bft_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedCommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedCommitMessage) ProtoMessage() {}

func (x *SignedCommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedCommitMessage.ProtoReflect.Descriptor instead.
func (*SignedCommitMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{13}
}

func (x *SignedCommitMessage) GetMessage() *CommitMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedCommitMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CheckpointMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceNum   int64                  `protobuf:"varint,1,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	NodeID        string                 `protobuf:"bytes,3,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointMessage) Reset() {
	*x = CheckpointMessage{}
	mi := &file_bft_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointMessage) ProtoMessage() {}

func (x *CheckpointMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointMessage.ProtoReflect.Descriptor instead.
func (*CheckpointMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{14}
}

func (x *CheckpointMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *CheckpointMessage) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CheckpointMessage) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type SignedCheckpointMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *CheckpointMessage     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedCheckpointMessage) Reset() {
	*x = SignedCheckpointMessage{}
	mi := &file_bft_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedCheckpointMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedCheckpointMessage) ProtoMessage() {}

func (x *SignedCheckpointMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedCheckpointMessage.ProtoReflect.Descriptor instead.
func (*SignedCheckpointMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{15}
}

func (x *SignedCheckpointMessage) GetMessage() *CheckpointMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedCheckpointMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type GetCheckpointMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceNum   int64                  `protobuf:"varint,1,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	NodeID        string                 `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckpointMessage) Reset() {
	*x = GetCheckpointMessage{}
	mi := &file_bft_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointMessage) ProtoMessage() {}

func (x *GetCheckpointMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointMessage.ProtoReflect.Descriptor instead.
func (*GetCheckpointMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{16}
}

func (x *GetCheckpointMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *GetCheckpointMessage) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        []byte                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Snapshot      map[string]int64       `protobuf:"bytes,2,rep,name=snapshot,proto3" json:"snapshot,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_bft_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{17}
}

func (x *Checkpoint) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *Checkpoint) GetSnapshot() map[string]int64 {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type PrepareProof struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	SignedPrePrepareMessage *SignedPrePrepareMessage `protobuf:"bytes,1,opt,name=signedPrePrepareMessage,proto3" json:"signedPrePrepareMessage,omitempty"`
	SignedPrepareMessage    *SignedPrepareMessage    `protobuf:"bytes,2,opt,name=signedPrepareMessage,proto3" json:"signedPrepareMessage,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PrepareProof) Reset() {
	*x = PrepareProof{}
	mi := &file_bft_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareProof) ProtoMessage() {}

func (x *PrepareProof) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareProof.ProtoReflect.Descriptor instead.
func (*PrepareProof) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{18}
}

func (x *PrepareProof) GetSignedPrePrepareMessage() *SignedPrePrepareMessage {
	if x != nil {
		return x.SignedPrePrepareMessage
	}
	return nil
}

func (x *PrepareProof) GetSignedPrepareMessage() *SignedPrepareMessage {
	if x != nil {
		return x.SignedPrepareMessage
	}
	return nil
}

type ViewChangeMessage struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	ViewNumber         int64                      `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	SequenceNum        int64                      `protobuf:"varint,2,opt,name=sequenceNum,proto3" json:"sequenceNum,omitempty"`
	CheckpointMessages []*SignedCheckpointMessage `protobuf:"bytes,3,rep,name=checkpointMessages,proto3" json:"checkpointMessages,omitempty"`
	PreparedSet        []*PrepareProof            `protobuf:"bytes,4,rep,name=preparedSet,proto3" json:"preparedSet,omitempty"`
	NodeID             string                     `protobuf:"bytes,5,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ViewChangeMessage) Reset() {
	*x = ViewChangeMessage{}
	mi := &file_bft_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewChangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewChangeMessage) ProtoMessage() {}

func (x *ViewChangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewChangeMessage.ProtoReflect.Descriptor instead.
func (*ViewChangeMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{19}
}

func (x *ViewChangeMessage) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *ViewChangeMessage) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *ViewChangeMessage) GetCheckpointMessages() []*SignedCheckpointMessage {
	if x != nil {
		return x.CheckpointMessages
	}
	return nil
}

func (x *ViewChangeMessage) GetPreparedSet() []*PrepareProof {
	if x != nil {
		return x.PreparedSet
	}
	return nil
}

func (x *ViewChangeMessage) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type SignedViewChangeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ViewChangeMessage     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedViewChangeMessage) Reset() {
	*x = SignedViewChangeMessage{}
	mi := &file_bft_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedViewChangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedViewChangeMessage) ProtoMessage() {}

func (x *SignedViewChangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedViewChangeMessage.ProtoReflect.Descriptor instead.
func (*SignedViewChangeMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{20}
}

func (x *SignedViewChangeMessage) GetMessage() *ViewChangeMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedViewChangeMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type NewViewMessage struct {
	state                    protoimpl.MessageState     `protogen:"open.v1"`
	ViewNumber               int64                      `protobuf:"varint,1,opt,name=viewNumber,proto3" json:"viewNumber,omitempty"`
	SignedViewChangeMessages []*SignedViewChangeMessage `protobuf:"bytes,2,rep,name=signedViewChangeMessages,proto3" json:"signedViewChangeMessages,omitempty"`
	SignedPrePrepareMessages []*SignedPrePrepareMessage `protobuf:"bytes,3,rep,name=signedPrePrepareMessages,proto3" json:"signedPrePrepareMessages,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *NewViewMessage) Reset() {
	*x = NewViewMessage{}
	mi := &file_bft_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewMessage) ProtoMessage() {}

func (x *NewViewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewMessage.ProtoReflect.Descriptor instead.
func (*NewViewMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{21}
}

func (x *NewViewMessage) GetViewNumber() int64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *NewViewMessage) GetSignedViewChangeMessages() []*SignedViewChangeMessage {
	if x != nil {
		return x.SignedViewChangeMessages
	}
	return nil
}

func (x *NewViewMessage) GetSignedPrePrepareMessages() []*SignedPrePrepareMessage {
	if x != nil {
		return x.SignedPrePrepareMessages
	}
	return nil
}

type SignedNewViewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *NewViewMessage        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedNewViewMessage) Reset() {
	*x = SignedNewViewMessage{}
	mi := &file_bft_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedNewViewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedNewViewMessage) ProtoMessage() {}

func (x *SignedNewViewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedNewViewMessage.ProtoReflect.Descriptor instead.
func (*SignedNewViewMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{22}
}

func (x *SignedNewViewMessage) GetMessage() *NewViewMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedNewViewMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type GetRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        []byte                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	NodeID        string                 `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestMessage) Reset() {
	*x = GetRequestMessage{}
	mi := &file_bft_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestMessage) ProtoMessage() {}

func (x *GetRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestMessage.ProtoReflect.Descriptor instead.
func (*GetRequestMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{23}
}

func (x *GetRequestMessage) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *GetRequestMessage) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type ChangeStatusMessage struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Alive                   bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	Byzantine               bool                   `protobuf:"varint,2,opt,name=byzantine,proto3" json:"byzantine,omitempty"`
	SignAttack              bool                   `protobuf:"varint,3,opt,name=signAttack,proto3" json:"signAttack,omitempty"`
	CrashAttack             bool                   `protobuf:"varint,4,opt,name=crashAttack,proto3" json:"crashAttack,omitempty"`
	DarkAttack              bool                   `protobuf:"varint,5,opt,name=darkAttack,proto3" json:"darkAttack,omitempty"`
	DarkAttackNodes         []string               `protobuf:"bytes,6,rep,name=darkAttackNodes,proto3" json:"darkAttackNodes,omitempty"`
	TimeAttack              bool                   `protobuf:"varint,7,opt,name=timeAttack,proto3" json:"timeAttack,omitempty"`
	EquivocationAttack      bool                   `protobuf:"varint,8,opt,name=equivocationAttack,proto3" json:"equivocationAttack,omitempty"`
	EquivocationAttackNodes []string               `protobuf:"bytes,9,rep,name=equivocationAttackNodes,proto3" json:"equivocationAttackNodes,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ChangeStatusMessage) Reset() {
	*x = ChangeStatusMessage{}
	mi := &file_bft_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStatusMessage) ProtoMessage() {}

func (x *ChangeStatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bft_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStatusMessage.ProtoReflect.Descriptor instead.
func (*ChangeStatusMessage) Descriptor() ([]byte, []int) {
	return file_bft_proto_rawDescGZIP(), []int{24}
}

func (x *ChangeStatusMessage) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *ChangeStatusMessage) GetByzantine() bool {
	if x != nil {
		return x.Byzantine
	}
	return false
}

func (x *ChangeStatusMessage) GetSignAttack() bool {
	if x != nil {
		return x.SignAttack
	}
	return false
}

func (x *ChangeStatusMessage) GetCrashAttack() bool {
	if x != nil {
		return x.CrashAttack
	}
	return false
}

func (x *ChangeStatusMessage) GetDarkAttack() bool {
	if x != nil {
		return x.DarkAttack
	}
	return false
}

func (x *ChangeStatusMessage) GetDarkAttackNodes() []string {
	if x != nil {
		return x.DarkAttackNodes
	}
	return nil
}

func (x *ChangeStatusMessage) GetTimeAttack() bool {
	if x != nil {
		return x.TimeAttack
	}
	return false
}

func (x *ChangeStatusMessage) GetEquivocationAttack() bool {
	if x != nil {
		return x.EquivocationAttack
	}
	return false
}

func (x *ChangeStatusMessage) GetEquivocationAttackNodes() []string {
	if x != nil {
		return x.EquivocationAttackNodes
	}
	return nil
}

var File_bft_proto protoreflect.FileDescriptor

const file_bft_proto_rawDesc = "" +
	"\n" +
	"\tbft.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"K\n" +
	"\rStatusRequest\x12\x18\n" +
	"\atestSet\x18\x01 \x01(\x03R\atestSet\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\"0\n" +
	"\fResetRequest\x12 \n" +
	"\vinitBalance\x18\x01 \x01(\x03R\vinitBalance\"\xeb\x02\n" +
	"\x13TransactionResponse\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x16\n" +
	"\x06nodeID\x18\x04 \x01(\tR\x06nodeID\x12\x16\n" +
	"\x06result\x18\x05 \x01(\x03R\x06result\x12G\n" +
	"\n" +
	"resultData\x18\x06 \x03(\v2'.pb.TransactionResponse.ResultDataEntryR\n" +
	"resultData\x120\n" +
	"\vscanResults\x18\a \x03(\v2\x0e.pb.ScanResultR\vscanResults\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x1a=\n" +
	"\x0fResultDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"{\n" +
	"\n" +
	"ScanResult\x122\n" +
	"\x06fields\x18\x01 \x03(\v2\x1a.pb.ScanResult.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"l\n" +
	"\x19SignedTransactionResponse\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x17.pb.TransactionResponseR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"}\n" +
	"\x12TransactionRequest\x121\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0f.pb.TransactionR\vtransaction\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\"j\n" +
	"\x18SignedTransactionRequest\x120\n" +
	"\arequest\x18\x01 \x01(\v2\x16.pb.TransactionRequestR\arequest\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xd7\x02\n" +
	"\vTransaction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x14\n" +
	"\x05table\x18\x05 \x01(\tR\x05table\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x123\n" +
	"\x06values\x18\a \x03(\v2\x1b.pb.Transaction.ValuesEntryR\x06values\x12\x16\n" +
	"\x06fields\x18\b \x03(\tR\x06fields\x12\x1a\n" +
	"\bstartKey\x18\t \x01(\tR\bstartKey\x12\x1c\n" +
	"\tscanCount\x18\n" +
	" \x01(\x03R\tscanCount\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"m\n" +
	"\x11PrePrepareMessage\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\"\xa0\x01\n" +
	"\x17SignedPrePrepareMessage\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.pb.PrePrepareMessageR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x126\n" +
	"\arequest\x18\x03 \x01(\v2\x1c.pb.SignedTransactionRequestR\arequest\"\x82\x01\n" +
	"\x0ePrepareMessage\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x16\n" +
	"\x06nodeID\x18\x04 \x01(\tR\x06nodeID\"\x82\x01\n" +
	"\x14SignedPrepareMessage\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.pb.PrepareMessageR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1e\n" +
	"\n" +
	"signature2\x18\x03 \x01(\fR\n" +
	"signature2\"\x81\x01\n" +
	"\rCommitMessage\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x16\n" +
	"\x06nodeID\x18\x04 \x01(\tR\x06nodeID\"`\n" +
	"\x13SignedCommitMessage\x12+\n" +
	"\amessage\x18\x01 \x01(\v2\x11.pb.CommitMessageR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"e\n" +
	"\x11CheckpointMessage\x12 \n" +
	"\vsequenceNum\x18\x01 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12\x16\n" +
	"\x06nodeID\x18\x03 \x01(\tR\x06nodeID\"h\n" +
	"\x17SignedCheckpointMessage\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.pb.CheckpointMessageR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"P\n" +
	"\x14GetCheckpointMessage\x12 \n" +
	"\vsequenceNum\x18\x01 \x01(\x03R\vsequenceNum\x12\x16\n" +
	"\x06nodeID\x18\x02 \x01(\tR\x06nodeID\"\x9b\x01\n" +
	"\n" +
	"Checkpoint\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\x128\n" +
	"\bsnapshot\x18\x02 \x03(\v2\x1c.pb.Checkpoint.SnapshotEntryR\bsnapshot\x1a;\n" +
	"\rSnapshotEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xb3\x01\n" +
	"\fPrepareProof\x12U\n" +
	"\x17signedPrePrepareMessage\x18\x01 \x01(\v2\x1b.pb.SignedPrePrepareMessageR\x17signedPrePrepareMessage\x12L\n" +
	"\x14signedPrepareMessage\x18\x02 \x01(\v2\x18.pb.SignedPrepareMessageR\x14signedPrepareMessage\"\xee\x01\n" +
	"\x11ViewChangeMessage\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12 \n" +
	"\vsequenceNum\x18\x02 \x01(\x03R\vsequenceNum\x12K\n" +
	"\x12checkpointMessages\x18\x03 \x03(\v2\x1b.pb.SignedCheckpointMessageR\x12checkpointMessages\x122\n" +
	"\vpreparedSet\x18\x04 \x03(\v2\x10.pb.PrepareProofR\vpreparedSet\x12\x16\n" +
	"\x06nodeID\x18\x05 \x01(\tR\x06nodeID\"h\n" +
	"\x17SignedViewChangeMessage\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.pb.ViewChangeMessageR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xe2\x01\n" +
	"\x0eNewViewMessage\x12\x1e\n" +
	"\n" +
	"viewNumber\x18\x01 \x01(\x03R\n" +
	"viewNumber\x12W\n" +
	"\x18signedViewChangeMessages\x18\x02 \x03(\v2\x1b.pb.SignedViewChangeMessageR\x18signedViewChangeMessages\x12W\n" +
	"\x18signedPrePrepareMessages\x18\x03 \x03(\v2\x1b.pb.SignedPrePrepareMessageR\x18signedPrePrepareMessages\"b\n" +
	"\x14SignedNewViewMessage\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.pb.NewViewMessageR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"C\n" +
	"\x11GetRequestMessage\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\x12\x16\n" +
	"\x06nodeID\x18\x02 \x01(\tR\x06nodeID\"\xdf\x02\n" +
	"\x13ChangeStatusMessage\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12\x1c\n" +
	"\tbyzantine\x18\x02 \x01(\bR\tbyzantine\x12\x1e\n" +
	"\n" +
	"signAttack\x18\x03 \x01(\bR\n" +
	"signAttack\x12 \n" +
	"\vcrashAttack\x18\x04 \x01(\bR\vcrashAttack\x12\x1e\n" +
	"\n" +
	"darkAttack\x18\x05 \x01(\bR\n" +
	"darkAttack\x12(\n" +
	"\x0fdarkAttackNodes\x18\x06 \x03(\tR\x0fdarkAttackNodes\x12\x1e\n" +
	"\n" +
	"timeAttack\x18\a \x01(\bR\n" +
	"timeAttack\x12.\n" +
	"\x12equivocationAttack\x18\b \x01(\bR\x12equivocationAttack\x128\n" +
	"\x17equivocationAttackNodes\x18\t \x03(\tR\x17equivocationAttackNodes2\x94\t\n" +
	"\x0eLinearPBFTNode\x12G\n" +
	"\x0fTransferRequest\x12\x1c.pb.SignedTransactionRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x0fReadOnlyRequest\x12\x1c.pb.SignedTransactionRequest\x1a\x1d.pb.SignedTransactionResponse\x12J\n" +
	"\x11PrePrepareRequest\x12\x1b.pb.SignedPrePrepareMessage\x1a\x18.pb.SignedPrepareMessage\x12C\n" +
	"\x0ePrepareRequest\x12\x18.pb.SignedPrepareMessage\x1a\x17.pb.SignedCommitMessage\x12@\n" +
	"\rCommitRequest\x12\x17.pb.SignedCommitMessage\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x11CheckpointRequest\x12\x1b.pb.SignedCheckpointMessage\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x11ViewChangeRequest\x12\x1b.pb.SignedViewChangeMessage\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x0eNewViewRequest\x12\x18.pb.SignedNewViewMessage\x1a\x18.pb.SignedPrepareMessage0\x01\x12A\n" +
	"\n" +
	"GetRequest\x12\x15.pb.GetRequestMessage\x1a\x1c.pb.SignedTransactionRequest\x129\n" +
	"\rGetCheckpoint\x12\x18.pb.GetCheckpointMessage\x1a\x0e.pb.Checkpoint\x12?\n" +
	"\bPrintLog\x12\x1b.google.protobuf.Int64Value\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\aPrintDB\x12\x1b.google.protobuf.Int64Value\x1a\x16.google.protobuf.Empty\x128\n" +
	"\vPrintStatus\x12\x11.pb.StatusRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\tPrintView\x12\x1b.google.protobuf.Int64Value\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x0fReconfigureNode\x12\x17.pb.ChangeStatusMessage\x1a\x16.google.protobuf.Empty\x125\n" +
	"\tResetNode\x12\x10.pb.ResetRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fBenchmarkRPC\x12\x1c.pb.SignedTransactionRequest\x1a\x16.google.protobuf.Empty2\\\n" +
	"\x13LinearPBFTClientApp\x12E\n" +
	"\fReceiveReply\x12\x1d.pb.SignedTransactionResponse\x1a\x16.google.protobuf.EmptyB$Z\"github.com/mavleo96/linear-pbft/pbb\x06proto3"

var (
	file_bft_proto_rawDescOnce sync.Once
	file_bft_proto_rawDescData []byte
)

func file_bft_proto_rawDescGZIP() []byte {
	file_bft_proto_rawDescOnce.Do(func() {
		file_bft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bft_proto_rawDesc), len(file_bft_proto_rawDesc)))
	})
	return file_bft_proto_rawDescData
}

var file_bft_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_bft_proto_goTypes = []any{
	(*StatusRequest)(nil),             // 0: pb.StatusRequest
	(*ResetRequest)(nil),              // 1: pb.ResetRequest
	(*TransactionResponse)(nil),       // 2: pb.TransactionResponse
	(*ScanResult)(nil),                // 3: pb.ScanResult
	(*SignedTransactionResponse)(nil), // 4: pb.SignedTransactionResponse
	(*TransactionRequest)(nil),        // 5: pb.TransactionRequest
	(*SignedTransactionRequest)(nil),  // 6: pb.SignedTransactionRequest
	(*Transaction)(nil),               // 7: pb.Transaction
	(*PrePrepareMessage)(nil),         // 8: pb.PrePrepareMessage
	(*SignedPrePrepareMessage)(nil),   // 9: pb.SignedPrePrepareMessage
	(*PrepareMessage)(nil),            // 10: pb.PrepareMessage
	(*SignedPrepareMessage)(nil),      // 11: pb.SignedPrepareMessage
	(*CommitMessage)(nil),             // 12: pb.CommitMessage
	(*SignedCommitMessage)(nil),       // 13: pb.SignedCommitMessage
	(*CheckpointMessage)(nil),         // 14: pb.CheckpointMessage
	(*SignedCheckpointMessage)(nil),   // 15: pb.SignedCheckpointMessage
	(*GetCheckpointMessage)(nil),      // 16: pb.GetCheckpointMessage
	(*Checkpoint)(nil),                // 17: pb.Checkpoint
	(*PrepareProof)(nil),              // 18: pb.PrepareProof
	(*ViewChangeMessage)(nil),         // 19: pb.ViewChangeMessage
	(*SignedViewChangeMessage)(nil),   // 20: pb.SignedViewChangeMessage
	(*NewViewMessage)(nil),            // 21: pb.NewViewMessage
	(*SignedNewViewMessage)(nil),      // 22: pb.SignedNewViewMessage
	(*GetRequestMessage)(nil),         // 23: pb.GetRequestMessage
	(*ChangeStatusMessage)(nil),       // 24: pb.ChangeStatusMessage
	nil,                               // 25: pb.TransactionResponse.ResultDataEntry
	nil,                               // 26: pb.ScanResult.FieldsEntry
	nil,                               // 27: pb.Transaction.ValuesEntry
	nil,                               // 28: pb.Checkpoint.SnapshotEntry
	(*wrapperspb.Int64Value)(nil),     // 29: google.protobuf.Int64Value
	(*emptypb.Empty)(nil),             // 30: google.protobuf.Empty
}
var file_bft_proto_depIdxs = []int32{
	25, // 0: pb.TransactionResponse.resultData:type_name -> pb.TransactionResponse.ResultDataEntry
	3,  // 1: pb.TransactionResponse.scanResults:type_name -> pb.ScanResult
	26, // 2: pb.ScanResult.fields:type_name -> pb.ScanResult.FieldsEntry
	2,  // 3: pb.SignedTransactionResponse.message:type_name -> pb.TransactionResponse
	7,  // 4: pb.TransactionRequest.transaction:type_name -> pb.Transaction
	5,  // 5: pb.SignedTransactionRequest.request:type_name -> pb.TransactionRequest
	27, // 6: pb.Transaction.values:type_name -> pb.Transaction.ValuesEntry
	8,  // 7: pb.SignedPrePrepareMessage.message:type_name -> pb.PrePrepareMessage
	6,  // 8: pb.SignedPrePrepareMessage.request:type_name -> pb.SignedTransactionRequest
	10, // 9: pb.SignedPrepareMessage.message:type_name -> pb.PrepareMessage
	12, // 10: pb.SignedCommitMessage.message:type_name -> pb.CommitMessage
	14, // 11: pb.SignedCheckpointMessage.message:type_name -> pb.CheckpointMessage
	28, // 12: pb.Checkpoint.snapshot:type_name -> pb.Checkpoint.SnapshotEntry
	9,  // 13: pb.PrepareProof.signedPrePrepareMessage:type_name -> pb.SignedPrePrepareMessage
	11, // 14: pb.PrepareProof.signedPrepareMessage:type_name -> pb.SignedPrepareMessage
	15, // 15: pb.ViewChangeMessage.checkpointMessages:type_name -> pb.SignedCheckpointMessage
	18, // 16: pb.ViewChangeMessage.preparedSet:type_name -> pb.PrepareProof
	19, // 17: pb.SignedViewChangeMessage.message:type_name -> pb.ViewChangeMessage
	20, // 18: pb.NewViewMessage.signedViewChangeMessages:type_name -> pb.SignedViewChangeMessage
	9,  // 19: pb.NewViewMessage.signedPrePrepareMessages:type_name -> pb.SignedPrePrepareMessage
	21, // 20: pb.SignedNewViewMessage.message:type_name -> pb.NewViewMessage
	6,  // 21: pb.LinearPBFTNode.TransferRequest:input_type -> pb.SignedTransactionRequest
	6,  // 22: pb.LinearPBFTNode.ReadOnlyRequest:input_type -> pb.SignedTransactionRequest
	9,  // 23: pb.LinearPBFTNode.PrePrepareRequest:input_type -> pb.SignedPrePrepareMessage
	11, // 24: pb.LinearPBFTNode.PrepareRequest:input_type -> pb.SignedPrepareMessage
	13, // 25: pb.LinearPBFTNode.CommitRequest:input_type -> pb.SignedCommitMessage
	15, // 26: pb.LinearPBFTNode.CheckpointRequest:input_type -> pb.SignedCheckpointMessage
	20, // 27: pb.LinearPBFTNode.ViewChangeRequest:input_type -> pb.SignedViewChangeMessage
	22, // 28: pb.LinearPBFTNode.NewViewRequest:input_type -> pb.SignedNewViewMessage
	23, // 29: pb.LinearPBFTNode.GetRequest:input_type -> pb.GetRequestMessage
	16, // 30: pb.LinearPBFTNode.GetCheckpoint:input_type -> pb.GetCheckpointMessage
	29, // 31: pb.LinearPBFTNode.PrintLog:input_type -> google.protobuf.Int64Value
	29, // 32: pb.LinearPBFTNode.PrintDB:input_type -> google.protobuf.Int64Value
	0,  // 33: pb.LinearPBFTNode.PrintStatus:input_type -> pb.StatusRequest
	29, // 34: pb.LinearPBFTNode.PrintView:input_type -> google.protobuf.Int64Value
	24, // 35: pb.LinearPBFTNode.ReconfigureNode:input_type -> pb.ChangeStatusMessage
	1,  // 36: pb.LinearPBFTNode.ResetNode:input_type -> pb.ResetRequest
	6,  // 37: pb.LinearPBFTNode.BenchmarkRPC:input_type -> pb.SignedTransactionRequest
	4,  // 38: pb.LinearPBFTClientApp.ReceiveReply:input_type -> pb.SignedTransactionResponse
	30, // 39: pb.LinearPBFTNode.TransferRequest:output_type -> google.protobuf.Empty
	4,  // 40: pb.LinearPBFTNode.ReadOnlyRequest:output_type -> pb.SignedTransactionResponse
	11, // 41: pb.LinearPBFTNode.PrePrepareRequest:output_type -> pb.SignedPrepareMessage
	13, // 42: pb.LinearPBFTNode.PrepareRequest:output_type -> pb.SignedCommitMessage
	30, // 43: pb.LinearPBFTNode.CommitRequest:output_type -> google.protobuf.Empty
	30, // 44: pb.LinearPBFTNode.CheckpointRequest:output_type -> google.protobuf.Empty
	30, // 45: pb.LinearPBFTNode.ViewChangeRequest:output_type -> google.protobuf.Empty
	11, // 46: pb.LinearPBFTNode.NewViewRequest:output_type -> pb.SignedPrepareMessage
	6,  // 47: pb.LinearPBFTNode.GetRequest:output_type -> pb.SignedTransactionRequest
	17, // 48: pb.LinearPBFTNode.GetCheckpoint:output_type -> pb.Checkpoint
	30, // 49: pb.LinearPBFTNode.PrintLog:output_type -> google.protobuf.Empty
	30, // 50: pb.LinearPBFTNode.PrintDB:output_type -> google.protobuf.Empty
	30, // 51: pb.LinearPBFTNode.PrintStatus:output_type -> google.protobuf.Empty
	30, // 52: pb.LinearPBFTNode.PrintView:output_type -> google.protobuf.Empty
	30, // 53: pb.LinearPBFTNode.ReconfigureNode:output_type -> google.protobuf.Empty
	30, // 54: pb.LinearPBFTNode.ResetNode:output_type -> google.protobuf.Empty
	30, // 55: pb.LinearPBFTNode.BenchmarkRPC:output_type -> google.protobuf.Empty
	30, // 56: pb.LinearPBFTClientApp.ReceiveReply:output_type -> google.protobuf.Empty
	39, // [39:57] is the sub-list for method output_type
	21, // [21:39] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_bft_proto_init() }
func file_bft_proto_init() {
	if File_bft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bft_proto_rawDesc), len(file_bft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_bft_proto_goTypes,
		DependencyIndexes: file_bft_proto_depIdxs,
		MessageInfos:      file_bft_proto_msgTypes,
	}.Build()
	File_bft_proto = out.File
	file_bft_proto_goTypes = nil
	file_bft_proto_depIdxs = nil
}
