// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.1
// source: bft.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LinearPBFTNode_TransferRequest_FullMethodName   = "/pb.LinearPBFTNode/TransferRequest"
	LinearPBFTNode_ReadOnlyRequest_FullMethodName   = "/pb.LinearPBFTNode/ReadOnlyRequest"
	LinearPBFTNode_PrePrepareRequest_FullMethodName = "/pb.LinearPBFTNode/PrePrepareRequest"
	LinearPBFTNode_PrepareRequest_FullMethodName    = "/pb.LinearPBFTNode/PrepareRequest"
	LinearPBFTNode_CommitRequest_FullMethodName     = "/pb.LinearPBFTNode/CommitRequest"
	LinearPBFTNode_CheckPointRequest_FullMethodName = "/pb.LinearPBFTNode/CheckPointRequest"
	LinearPBFTNode_ViewChangeRequest_FullMethodName = "/pb.LinearPBFTNode/ViewChangeRequest"
	LinearPBFTNode_NewViewRequest_FullMethodName    = "/pb.LinearPBFTNode/NewViewRequest"
	LinearPBFTNode_GetRequest_FullMethodName        = "/pb.LinearPBFTNode/GetRequest"
	LinearPBFTNode_PrintLog_FullMethodName          = "/pb.LinearPBFTNode/PrintLog"
	LinearPBFTNode_PrintDB_FullMethodName           = "/pb.LinearPBFTNode/PrintDB"
	LinearPBFTNode_PrintStatus_FullMethodName       = "/pb.LinearPBFTNode/PrintStatus"
	LinearPBFTNode_ReconfigureNode_FullMethodName   = "/pb.LinearPBFTNode/ReconfigureNode"
	LinearPBFTNode_ResetNode_FullMethodName         = "/pb.LinearPBFTNode/ResetNode"
)

// LinearPBFTNodeClient is the client API for LinearPBFTNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinearPBFTNodeClient interface {
	TransferRequest(ctx context.Context, in *SignedTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadOnlyRequest(ctx context.Context, in *SignedTransactionRequest, opts ...grpc.CallOption) (*SignedTransactionResponse, error)
	PrePrepareRequest(ctx context.Context, in *SignedPrePrepareMessage, opts ...grpc.CallOption) (*SignedPrepareMessage, error)
	PrepareRequest(ctx context.Context, in *CollectedSignedPrepareMessage, opts ...grpc.CallOption) (*SignedCommitMessage, error)
	CommitRequest(ctx context.Context, in *CollectedSignedCommitMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CheckPointRequest(ctx context.Context, in *SignedCheckPointMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ViewChangeRequest(ctx context.Context, in *SignedViewChangeMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	NewViewRequest(ctx context.Context, in *SignedNewViewMessage, opts ...grpc.CallOption) (LinearPBFTNode_NewViewRequestClient, error)
	GetRequest(ctx context.Context, in *GetRequestMessage, opts ...grpc.CallOption) (*SignedTransactionRequest, error)
	PrintLog(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PrintDB(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PrintStatus(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReconfigureNode(ctx context.Context, in *ChangeStatusMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResetNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type linearPBFTNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewLinearPBFTNodeClient(cc grpc.ClientConnInterface) LinearPBFTNodeClient {
	return &linearPBFTNodeClient{cc}
}

func (c *linearPBFTNodeClient) TransferRequest(ctx context.Context, in *SignedTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTNode_TransferRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) ReadOnlyRequest(ctx context.Context, in *SignedTransactionRequest, opts ...grpc.CallOption) (*SignedTransactionResponse, error) {
	out := new(SignedTransactionResponse)
	err := c.cc.Invoke(ctx, LinearPBFTNode_ReadOnlyRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) PrePrepareRequest(ctx context.Context, in *SignedPrePrepareMessage, opts ...grpc.CallOption) (*SignedPrepareMessage, error) {
	out := new(SignedPrepareMessage)
	err := c.cc.Invoke(ctx, LinearPBFTNode_PrePrepareRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) PrepareRequest(ctx context.Context, in *CollectedSignedPrepareMessage, opts ...grpc.CallOption) (*SignedCommitMessage, error) {
	out := new(SignedCommitMessage)
	err := c.cc.Invoke(ctx, LinearPBFTNode_PrepareRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) CommitRequest(ctx context.Context, in *CollectedSignedCommitMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTNode_CommitRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) CheckPointRequest(ctx context.Context, in *SignedCheckPointMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTNode_CheckPointRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) ViewChangeRequest(ctx context.Context, in *SignedViewChangeMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTNode_ViewChangeRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) NewViewRequest(ctx context.Context, in *SignedNewViewMessage, opts ...grpc.CallOption) (LinearPBFTNode_NewViewRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &LinearPBFTNode_ServiceDesc.Streams[0], LinearPBFTNode_NewViewRequest_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &linearPBFTNodeNewViewRequestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LinearPBFTNode_NewViewRequestClient interface {
	Recv() (*SignedPrepareMessage, error)
	grpc.ClientStream
}

type linearPBFTNodeNewViewRequestClient struct {
	grpc.ClientStream
}

func (x *linearPBFTNodeNewViewRequestClient) Recv() (*SignedPrepareMessage, error) {
	m := new(SignedPrepareMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *linearPBFTNodeClient) GetRequest(ctx context.Context, in *GetRequestMessage, opts ...grpc.CallOption) (*SignedTransactionRequest, error) {
	out := new(SignedTransactionRequest)
	err := c.cc.Invoke(ctx, LinearPBFTNode_GetRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) PrintLog(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTNode_PrintLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) PrintDB(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTNode_PrintDB_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) PrintStatus(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTNode_PrintStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) ReconfigureNode(ctx context.Context, in *ChangeStatusMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTNode_ReconfigureNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) ResetNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTNode_ResetNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinearPBFTNodeServer is the server API for LinearPBFTNode service.
// All implementations must embed UnimplementedLinearPBFTNodeServer
// for forward compatibility
type LinearPBFTNodeServer interface {
	TransferRequest(context.Context, *SignedTransactionRequest) (*emptypb.Empty, error)
	ReadOnlyRequest(context.Context, *SignedTransactionRequest) (*SignedTransactionResponse, error)
	PrePrepareRequest(context.Context, *SignedPrePrepareMessage) (*SignedPrepareMessage, error)
	PrepareRequest(context.Context, *CollectedSignedPrepareMessage) (*SignedCommitMessage, error)
	CommitRequest(context.Context, *CollectedSignedCommitMessage) (*emptypb.Empty, error)
	CheckPointRequest(context.Context, *SignedCheckPointMessage) (*emptypb.Empty, error)
	ViewChangeRequest(context.Context, *SignedViewChangeMessage) (*emptypb.Empty, error)
	NewViewRequest(*SignedNewViewMessage, LinearPBFTNode_NewViewRequestServer) error
	GetRequest(context.Context, *GetRequestMessage) (*SignedTransactionRequest, error)
	PrintLog(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	PrintDB(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	PrintStatus(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error)
	ReconfigureNode(context.Context, *ChangeStatusMessage) (*emptypb.Empty, error)
	ResetNode(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedLinearPBFTNodeServer()
}

// UnimplementedLinearPBFTNodeServer must be embedded to have forward compatible implementations.
type UnimplementedLinearPBFTNodeServer struct {
}

func (UnimplementedLinearPBFTNodeServer) TransferRequest(context.Context, *SignedTransactionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferRequest not implemented")
}
func (UnimplementedLinearPBFTNodeServer) ReadOnlyRequest(context.Context, *SignedTransactionRequest) (*SignedTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadOnlyRequest not implemented")
}
func (UnimplementedLinearPBFTNodeServer) PrePrepareRequest(context.Context, *SignedPrePrepareMessage) (*SignedPrepareMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrePrepareRequest not implemented")
}
func (UnimplementedLinearPBFTNodeServer) PrepareRequest(context.Context, *CollectedSignedPrepareMessage) (*SignedCommitMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareRequest not implemented")
}
func (UnimplementedLinearPBFTNodeServer) CommitRequest(context.Context, *CollectedSignedCommitMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitRequest not implemented")
}
func (UnimplementedLinearPBFTNodeServer) CheckPointRequest(context.Context, *SignedCheckPointMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPointRequest not implemented")
}
func (UnimplementedLinearPBFTNodeServer) ViewChangeRequest(context.Context, *SignedViewChangeMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewChangeRequest not implemented")
}
func (UnimplementedLinearPBFTNodeServer) NewViewRequest(*SignedNewViewMessage, LinearPBFTNode_NewViewRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method NewViewRequest not implemented")
}
func (UnimplementedLinearPBFTNodeServer) GetRequest(context.Context, *GetRequestMessage) (*SignedTransactionRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequest not implemented")
}
func (UnimplementedLinearPBFTNodeServer) PrintLog(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintLog not implemented")
}
func (UnimplementedLinearPBFTNodeServer) PrintDB(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintDB not implemented")
}
func (UnimplementedLinearPBFTNodeServer) PrintStatus(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintStatus not implemented")
}
func (UnimplementedLinearPBFTNodeServer) ReconfigureNode(context.Context, *ChangeStatusMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReconfigureNode not implemented")
}
func (UnimplementedLinearPBFTNodeServer) ResetNode(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetNode not implemented")
}
func (UnimplementedLinearPBFTNodeServer) mustEmbedUnimplementedLinearPBFTNodeServer() {}

// UnsafeLinearPBFTNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinearPBFTNodeServer will
// result in compilation errors.
type UnsafeLinearPBFTNodeServer interface {
	mustEmbedUnimplementedLinearPBFTNodeServer()
}

func RegisterLinearPBFTNodeServer(s grpc.ServiceRegistrar, srv LinearPBFTNodeServer) {
	s.RegisterService(&LinearPBFTNode_ServiceDesc, srv)
}

func _LinearPBFTNode_TransferRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).TransferRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_TransferRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).TransferRequest(ctx, req.(*SignedTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_ReadOnlyRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).ReadOnlyRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_ReadOnlyRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).ReadOnlyRequest(ctx, req.(*SignedTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_PrePrepareRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedPrePrepareMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).PrePrepareRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_PrePrepareRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).PrePrepareRequest(ctx, req.(*SignedPrePrepareMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_PrepareRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectedSignedPrepareMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).PrepareRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_PrepareRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).PrepareRequest(ctx, req.(*CollectedSignedPrepareMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_CommitRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectedSignedCommitMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).CommitRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_CommitRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).CommitRequest(ctx, req.(*CollectedSignedCommitMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_CheckPointRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedCheckPointMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).CheckPointRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_CheckPointRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).CheckPointRequest(ctx, req.(*SignedCheckPointMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_ViewChangeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedViewChangeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).ViewChangeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_ViewChangeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).ViewChangeRequest(ctx, req.(*SignedViewChangeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_NewViewRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SignedNewViewMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LinearPBFTNodeServer).NewViewRequest(m, &linearPBFTNodeNewViewRequestServer{stream})
}

type LinearPBFTNode_NewViewRequestServer interface {
	Send(*SignedPrepareMessage) error
	grpc.ServerStream
}

type linearPBFTNodeNewViewRequestServer struct {
	grpc.ServerStream
}

func (x *linearPBFTNodeNewViewRequestServer) Send(m *SignedPrepareMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _LinearPBFTNode_GetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).GetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_GetRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).GetRequest(ctx, req.(*GetRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_PrintLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).PrintLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_PrintLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).PrintLog(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_PrintDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).PrintDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_PrintDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).PrintDB(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_PrintStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).PrintStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_PrintStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).PrintStatus(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_ReconfigureNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeStatusMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).ReconfigureNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_ReconfigureNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).ReconfigureNode(ctx, req.(*ChangeStatusMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_ResetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).ResetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_ResetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).ResetNode(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// LinearPBFTNode_ServiceDesc is the grpc.ServiceDesc for LinearPBFTNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinearPBFTNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LinearPBFTNode",
	HandlerType: (*LinearPBFTNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferRequest",
			Handler:    _LinearPBFTNode_TransferRequest_Handler,
		},
		{
			MethodName: "ReadOnlyRequest",
			Handler:    _LinearPBFTNode_ReadOnlyRequest_Handler,
		},
		{
			MethodName: "PrePrepareRequest",
			Handler:    _LinearPBFTNode_PrePrepareRequest_Handler,
		},
		{
			MethodName: "PrepareRequest",
			Handler:    _LinearPBFTNode_PrepareRequest_Handler,
		},
		{
			MethodName: "CommitRequest",
			Handler:    _LinearPBFTNode_CommitRequest_Handler,
		},
		{
			MethodName: "CheckPointRequest",
			Handler:    _LinearPBFTNode_CheckPointRequest_Handler,
		},
		{
			MethodName: "ViewChangeRequest",
			Handler:    _LinearPBFTNode_ViewChangeRequest_Handler,
		},
		{
			MethodName: "GetRequest",
			Handler:    _LinearPBFTNode_GetRequest_Handler,
		},
		{
			MethodName: "PrintLog",
			Handler:    _LinearPBFTNode_PrintLog_Handler,
		},
		{
			MethodName: "PrintDB",
			Handler:    _LinearPBFTNode_PrintDB_Handler,
		},
		{
			MethodName: "PrintStatus",
			Handler:    _LinearPBFTNode_PrintStatus_Handler,
		},
		{
			MethodName: "ReconfigureNode",
			Handler:    _LinearPBFTNode_ReconfigureNode_Handler,
		},
		{
			MethodName: "ResetNode",
			Handler:    _LinearPBFTNode_ResetNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NewViewRequest",
			Handler:       _LinearPBFTNode_NewViewRequest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bft.proto",
}

const (
	LinearPBFTClientApp_ReceiveReply_FullMethodName = "/pb.LinearPBFTClientApp/ReceiveReply"
)

// LinearPBFTClientAppClient is the client API for LinearPBFTClientApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinearPBFTClientAppClient interface {
	ReceiveReply(ctx context.Context, in *SignedTransactionResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type linearPBFTClientAppClient struct {
	cc grpc.ClientConnInterface
}

func NewLinearPBFTClientAppClient(cc grpc.ClientConnInterface) LinearPBFTClientAppClient {
	return &linearPBFTClientAppClient{cc}
}

func (c *linearPBFTClientAppClient) ReceiveReply(ctx context.Context, in *SignedTransactionResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTClientApp_ReceiveReply_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinearPBFTClientAppServer is the server API for LinearPBFTClientApp service.
// All implementations must embed UnimplementedLinearPBFTClientAppServer
// for forward compatibility
type LinearPBFTClientAppServer interface {
	ReceiveReply(context.Context, *SignedTransactionResponse) (*emptypb.Empty, error)
	mustEmbedUnimplementedLinearPBFTClientAppServer()
}

// UnimplementedLinearPBFTClientAppServer must be embedded to have forward compatible implementations.
type UnimplementedLinearPBFTClientAppServer struct {
}

func (UnimplementedLinearPBFTClientAppServer) ReceiveReply(context.Context, *SignedTransactionResponse) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveReply not implemented")
}
func (UnimplementedLinearPBFTClientAppServer) mustEmbedUnimplementedLinearPBFTClientAppServer() {}

// UnsafeLinearPBFTClientAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinearPBFTClientAppServer will
// result in compilation errors.
type UnsafeLinearPBFTClientAppServer interface {
	mustEmbedUnimplementedLinearPBFTClientAppServer()
}

func RegisterLinearPBFTClientAppServer(s grpc.ServiceRegistrar, srv LinearPBFTClientAppServer) {
	s.RegisterService(&LinearPBFTClientApp_ServiceDesc, srv)
}

func _LinearPBFTClientApp_ReceiveReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedTransactionResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTClientAppServer).ReceiveReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTClientApp_ReceiveReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTClientAppServer).ReceiveReply(ctx, req.(*SignedTransactionResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// LinearPBFTClientApp_ServiceDesc is the grpc.ServiceDesc for LinearPBFTClientApp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinearPBFTClientApp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LinearPBFTClientApp",
	HandlerType: (*LinearPBFTClientAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveReply",
			Handler:    _LinearPBFTClientApp_ReceiveReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bft.proto",
}
