// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.1
// source: bft.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LinearPBFT_TransferRequest_FullMethodName = "/pb.LinearPBFT/TransferRequest"
)

// LinearPBFTClient is the client API for LinearPBFT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinearPBFTClient interface {
	TransferRequest(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type linearPBFTClient struct {
	cc grpc.ClientConnInterface
}

func NewLinearPBFTClient(cc grpc.ClientConnInterface) LinearPBFTClient {
	return &linearPBFTClient{cc}
}

func (c *linearPBFTClient) TransferRequest(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFT_TransferRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinearPBFTServer is the server API for LinearPBFT service.
// All implementations must embed UnimplementedLinearPBFTServer
// for forward compatibility
type LinearPBFTServer interface {
	TransferRequest(context.Context, *TransactionRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedLinearPBFTServer()
}

// UnimplementedLinearPBFTServer must be embedded to have forward compatible implementations.
type UnimplementedLinearPBFTServer struct {
}

func (UnimplementedLinearPBFTServer) TransferRequest(context.Context, *TransactionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferRequest not implemented")
}
func (UnimplementedLinearPBFTServer) mustEmbedUnimplementedLinearPBFTServer() {}

// UnsafeLinearPBFTServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinearPBFTServer will
// result in compilation errors.
type UnsafeLinearPBFTServer interface {
	mustEmbedUnimplementedLinearPBFTServer()
}

func RegisterLinearPBFTServer(s grpc.ServiceRegistrar, srv LinearPBFTServer) {
	s.RegisterService(&LinearPBFT_ServiceDesc, srv)
}

func _LinearPBFT_TransferRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTServer).TransferRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFT_TransferRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTServer).TransferRequest(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LinearPBFT_ServiceDesc is the grpc.ServiceDesc for LinearPBFT service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinearPBFT_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LinearPBFT",
	HandlerType: (*LinearPBFTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferRequest",
			Handler:    _LinearPBFT_TransferRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bft.proto",
}
