// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.1
// source: bft.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LinearPBFTNode_TransferRequest_FullMethodName = "/pb.LinearPBFTNode/TransferRequest"
	LinearPBFTNode_PrePrepare_FullMethodName      = "/pb.LinearPBFTNode/PrePrepare"
	LinearPBFTNode_Prepare_FullMethodName         = "/pb.LinearPBFTNode/Prepare"
	LinearPBFTNode_Commit_FullMethodName          = "/pb.LinearPBFTNode/Commit"
)

// LinearPBFTNodeClient is the client API for LinearPBFTNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinearPBFTNodeClient interface {
	TransferRequest(ctx context.Context, in *SignedTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PrePrepare(ctx context.Context, in *SignedPrePrepareMessage, opts ...grpc.CallOption) (*SignedPrepareMessage, error)
	Prepare(ctx context.Context, in *CollectedSignedPrepareMessage, opts ...grpc.CallOption) (*SignedCommitMessage, error)
	Commit(ctx context.Context, in *CollectedSignedCommitMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type linearPBFTNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewLinearPBFTNodeClient(cc grpc.ClientConnInterface) LinearPBFTNodeClient {
	return &linearPBFTNodeClient{cc}
}

func (c *linearPBFTNodeClient) TransferRequest(ctx context.Context, in *SignedTransactionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTNode_TransferRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) PrePrepare(ctx context.Context, in *SignedPrePrepareMessage, opts ...grpc.CallOption) (*SignedPrepareMessage, error) {
	out := new(SignedPrepareMessage)
	err := c.cc.Invoke(ctx, LinearPBFTNode_PrePrepare_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) Prepare(ctx context.Context, in *CollectedSignedPrepareMessage, opts ...grpc.CallOption) (*SignedCommitMessage, error) {
	out := new(SignedCommitMessage)
	err := c.cc.Invoke(ctx, LinearPBFTNode_Prepare_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linearPBFTNodeClient) Commit(ctx context.Context, in *CollectedSignedCommitMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTNode_Commit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinearPBFTNodeServer is the server API for LinearPBFTNode service.
// All implementations must embed UnimplementedLinearPBFTNodeServer
// for forward compatibility
type LinearPBFTNodeServer interface {
	TransferRequest(context.Context, *SignedTransactionRequest) (*emptypb.Empty, error)
	PrePrepare(context.Context, *SignedPrePrepareMessage) (*SignedPrepareMessage, error)
	Prepare(context.Context, *CollectedSignedPrepareMessage) (*SignedCommitMessage, error)
	Commit(context.Context, *CollectedSignedCommitMessage) (*emptypb.Empty, error)
	mustEmbedUnimplementedLinearPBFTNodeServer()
}

// UnimplementedLinearPBFTNodeServer must be embedded to have forward compatible implementations.
type UnimplementedLinearPBFTNodeServer struct {
}

func (UnimplementedLinearPBFTNodeServer) TransferRequest(context.Context, *SignedTransactionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferRequest not implemented")
}
func (UnimplementedLinearPBFTNodeServer) PrePrepare(context.Context, *SignedPrePrepareMessage) (*SignedPrepareMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrePrepare not implemented")
}
func (UnimplementedLinearPBFTNodeServer) Prepare(context.Context, *CollectedSignedPrepareMessage) (*SignedCommitMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedLinearPBFTNodeServer) Commit(context.Context, *CollectedSignedCommitMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedLinearPBFTNodeServer) mustEmbedUnimplementedLinearPBFTNodeServer() {}

// UnsafeLinearPBFTNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinearPBFTNodeServer will
// result in compilation errors.
type UnsafeLinearPBFTNodeServer interface {
	mustEmbedUnimplementedLinearPBFTNodeServer()
}

func RegisterLinearPBFTNodeServer(s grpc.ServiceRegistrar, srv LinearPBFTNodeServer) {
	s.RegisterService(&LinearPBFTNode_ServiceDesc, srv)
}

func _LinearPBFTNode_TransferRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).TransferRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_TransferRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).TransferRequest(ctx, req.(*SignedTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_PrePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedPrePrepareMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).PrePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_PrePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).PrePrepare(ctx, req.(*SignedPrePrepareMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectedSignedPrepareMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).Prepare(ctx, req.(*CollectedSignedPrepareMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinearPBFTNode_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectedSignedCommitMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTNodeServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTNode_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTNodeServer).Commit(ctx, req.(*CollectedSignedCommitMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// LinearPBFTNode_ServiceDesc is the grpc.ServiceDesc for LinearPBFTNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinearPBFTNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LinearPBFTNode",
	HandlerType: (*LinearPBFTNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferRequest",
			Handler:    _LinearPBFTNode_TransferRequest_Handler,
		},
		{
			MethodName: "PrePrepare",
			Handler:    _LinearPBFTNode_PrePrepare_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _LinearPBFTNode_Prepare_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _LinearPBFTNode_Commit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bft.proto",
}

const (
	LinearPBFTClientApp_ReceiveReply_FullMethodName = "/pb.LinearPBFTClientApp/ReceiveReply"
)

// LinearPBFTClientAppClient is the client API for LinearPBFTClientApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinearPBFTClientAppClient interface {
	ReceiveReply(ctx context.Context, in *SignedTransactionResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type linearPBFTClientAppClient struct {
	cc grpc.ClientConnInterface
}

func NewLinearPBFTClientAppClient(cc grpc.ClientConnInterface) LinearPBFTClientAppClient {
	return &linearPBFTClientAppClient{cc}
}

func (c *linearPBFTClientAppClient) ReceiveReply(ctx context.Context, in *SignedTransactionResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LinearPBFTClientApp_ReceiveReply_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinearPBFTClientAppServer is the server API for LinearPBFTClientApp service.
// All implementations must embed UnimplementedLinearPBFTClientAppServer
// for forward compatibility
type LinearPBFTClientAppServer interface {
	ReceiveReply(context.Context, *SignedTransactionResponse) (*emptypb.Empty, error)
	mustEmbedUnimplementedLinearPBFTClientAppServer()
}

// UnimplementedLinearPBFTClientAppServer must be embedded to have forward compatible implementations.
type UnimplementedLinearPBFTClientAppServer struct {
}

func (UnimplementedLinearPBFTClientAppServer) ReceiveReply(context.Context, *SignedTransactionResponse) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveReply not implemented")
}
func (UnimplementedLinearPBFTClientAppServer) mustEmbedUnimplementedLinearPBFTClientAppServer() {}

// UnsafeLinearPBFTClientAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinearPBFTClientAppServer will
// result in compilation errors.
type UnsafeLinearPBFTClientAppServer interface {
	mustEmbedUnimplementedLinearPBFTClientAppServer()
}

func RegisterLinearPBFTClientAppServer(s grpc.ServiceRegistrar, srv LinearPBFTClientAppServer) {
	s.RegisterService(&LinearPBFTClientApp_ServiceDesc, srv)
}

func _LinearPBFTClientApp_ReceiveReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedTransactionResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinearPBFTClientAppServer).ReceiveReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LinearPBFTClientApp_ReceiveReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinearPBFTClientAppServer).ReceiveReply(ctx, req.(*SignedTransactionResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// LinearPBFTClientApp_ServiceDesc is the grpc.ServiceDesc for LinearPBFTClientApp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinearPBFTClientApp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LinearPBFTClientApp",
	HandlerType: (*LinearPBFTClientAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveReply",
			Handler:    _LinearPBFTClientApp_ReceiveReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bft.proto",
}
